### ISSUE TITLE
Block/Layerednav.php line 63

### ISSUE THREAD

**Issue by hubi-moore** [magepow/magento-2-layered-navigation#4]
Block/Layerednav.php line 63

I think you should use floor 
  `$RangePrice['min'] = floor($min_price);`
instead of ceil here
  `$RangePrice['min'] = ceil($min_price);`
  
  eg.
  Minimal price is 2.50 - your version will output 3 instead of 2
  
Please consider correction but if I am wrong then correct me in the comment

**Comment by magiccart** [comment]
@hubi-moore Thanks for your report. I have updated fixed this.
